
server:
  context-path: "/"
  undertow:
    io-threads: 2
    worker-threads: 200
  port: 8888

grpc:
  client:
    graduation-project-provider:
      server-host: localhost
      serverPort: 7575
      enable-keep-alive: true
      keep-alive-delay: 5 # seconds

cors:
  mappings: /**
  allowedOrigins:



logging:
  level:
    cn.vpclub: INFO
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36})  - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: logs/application.log