
app:
  datasource:
    name: tms
    host: localhost:3306
    username: root
    password: 123456

server:
  undertow:
    io-threads: 2
    worker-threads: 100
  port: 0 # 自动分配端口

# 重要：grpc服务器使用的端口
grpc:
  server:
    port: 7575


spring:
  # 数据库配置
  datasource:
    name: ${app.datasource.name}
    url: jdbc:mysql://${app.datasource.host}/${app.datasource.name}?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    username: ${app.datasource.username}
    password: ${app.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true


mybatis:
  mapper-locations : "classpath:mapper/*Mapper.xml"

# LOGGING
logging:
  level:
    org.springframework: INFO
    cn.vpclub.spring.boot: INFO
    cn.vpclub.moses: DEBUG
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{64})  - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: logs/application.log